apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: amq
  name: amq
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: amq
    spec:
      containers:
      - name: amq
        image: rmohr/activemq:latest
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
        ports:
        - containerPort: 61616
  selector:
    matchLabels:
      app: amq
