apiVersion: v1
kind: Service
metadata:
  name: command-svc
  labels:
    app: command-svc
spec:
  type: LoadBalancer
  ports:
  - port: 9004
    targetPort: 9004
    protocol: TCP
    name: command-svc
  selector:
    app: command-svc
