apiVersion: v1
kind: Service
metadata:
  name: mqtt-svc
  labels:
    app: mqtt
spec:
  type: LoadBalancer
  ports:
    - port: 1883
      targetPort: 1883
      protocol: TCP
      name: mqtt
  selector:
    app: mqtt
