apiVersion: v1
kind: Service
metadata:
  name: state-svc
  labels:
    app: state-svc
spec:
  type: LoadBalancer
  ports:
    - port: 9006
      targetPort: 9006
      protocol: TCP
      name: state-svc
  selector:
    app: state-svc