apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: thing-svc
  name: thing-svc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: thing-svc
  template:
    metadata:
      labels:
        app: thing-svc
    spec:
      containers:
      - name: thing-svc
        image: thing-svc:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 9010
        volumeMounts:
          - name: data
            mountPath: /jasdb
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: production
        - name: JASDB_HOME
          value: /jasdb
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: thing-volume-claim