kind: PersistentVolume
apiVersion: v1
metadata:
  name: thing-volume
spec:
  storageClassName: hostpath
  capacity:
    storage: 4096Mi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/Users/renarj/docker/thing-svc"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: thing-volume-claim
spec:
  storageClassName: hostpath
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1024Mi